//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizzer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizzerDBEntities : DbContext
    {
        public QuizzerDBEntities()
            : base("name=QuizzerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeographyQuestion> GeographyQuestions { get; set; }
        public virtual DbSet<HistoryQuestion> HistoryQuestions { get; set; }
        public virtual DbSet<ScienceQuestion> ScienceQuestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
