//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeographyQuestion
    {
        public int Id { get; set; }
        public string createdBy { get; set; }
        public string question { get; set; }
        public string answerOne { get; set; }
        public string answerTwo { get; set; }
        public string answerThree { get; set; }
        public string answerFour { get; set; }
        public string correctAnswer { get; set; }
    }
}
